import 'server-only';
import { cookies } from 'next/headers';
import { createServerClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import { timingSafeEqual } from 'node:crypto';

export class AppError extends Error {constructor(message:string,public status=400,public code='invalid_request'){super(message);}}
export function env(name:string){const value=process.env[name];if(!value)throw new AppError('Servis ini belum diaktifkan oleh platform. Anda masih boleh mencuba demo.',503,'not_configured');return value;}
export function appUrl(){const origin=new URL(process.env.NEXT_PUBLIC_APP_URL||(process.env.NODE_ENV==='production'?'https://not-configured.invalid':'http://localhost:3000'));if(origin.hostname==='not-configured.invalid')throw new AppError('Alamat platform belum dikonfigurasi.',503);return origin.origin;}
export function db(){return createClient(env('NEXT_PUBLIC_SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});}
export async function authClient(){const store=await cookies();return createServerClient(env('NEXT_PUBLIC_SUPABASE_URL'),env('NEXT_PUBLIC_SUPABASE_ANON_KEY'),{cookies:{getAll:()=>store.getAll(),setAll:items=>{items.forEach(({name,value,options})=>store.set(name,value,options));}}});}
export async function requireUser(){const sb=await authClient();const {data:{user},error}=await sb.auth.getUser();if(error||!user||user.is_anonymous)throw new AppError('Sila log masuk untuk meneruskan.',401,'unauthenticated');return user;}
export async function ensureProfile(user:{id:string;email?:string;user_metadata?:Record<string,unknown>}){const result=await db().from('users').upsert({id:user.id,email:user.email||'',name:String(user.user_metadata?.name||user.user_metadata?.full_name||'Kreator').slice(0,80)},{onConflict:'id',ignoreDuplicates:true});checkDB(result.error);}
export function adminAllowed(id:string){return (process.env.ADMIN_USER_IDS||'').split(',').map(v=>v.trim()).filter(Boolean).includes(id);}
export function requireAdmin(id:string){if(!adminAllowed(id))throw new AppError('Akses pentadbir diperlukan.',403,'forbidden');}
export async function requireSubscription(userId:string){const {data,error}=await db().from('subscriptions').select('plan_id,status,current_period_end,provider_customer_id,provider_subscription_id').eq('user_id',userId).maybeSingle();checkDB(error);if(!data||data.status!=='active'||Date.parse(data.current_period_end)<=Date.now())throw new AppError('Pilih atau perbaharui pelan untuk menggunakan fungsi ini.',402,'subscription_required');return data;}
export function checkDB(error:{message:string;code?:string}|null){if(!error)return;const map:Record<string,[string,number]>={quota_exceeded:['Kredit bulan ini telah habis. Naik taraf pelan untuk terus mencipta.',429],subscription_required:['Langganan aktif diperlukan untuk menjana content.',402],not_found:['Post tidak ditemui.',404]};for(const [key,[msg,status]]of Object.entries(map))if(error.message.includes(key))throw new AppError(msg,status,key);throw new AppError('Data belum dapat disimpan atau dimuatkan. Cuba lagi sebentar.',500,error.code||'database_error');}
export async function rate(userId:string,action:string,limit=12){const {data,error}=await db().rpc('take_rate',{p_user:userId,p_action:action,p_limit:limit});checkDB(error);if(!data)throw new AppError('Terlalu banyak permintaan. Cuba lagi dalam satu minit.',429,'rate_limit');}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin)throw new AppError('Permintaan tidak sah.',403,'origin_required');const expected=new URL(req.url).origin;if(origin!==expected || (process.env.NODE_ENV==='production'&&origin!==appUrl()))throw new AppError('Permintaan tidak sah.',403,'invalid_origin');}
export function cronAuth(req:Request){const secret=env('CRON_SECRET');const provided=req.headers.get('authorization')||'';const expected=`Bearer ${secret}`;if(provided.length!==expected.length||!timingSafeEqual(Buffer.from(provided),Buffer.from(expected)))throw new AppError('Unauthorized',401);}
export async function readBody(req:Request,max=20_000){const reader=req.body?.getReader();if(!reader)throw new AppError('Data diperlukan.');const chunks:Uint8Array[]=[];let size=0;for(;;){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new AppError('Permintaan terlalu besar.',413);}chunks.push(value);}return Buffer.concat(chunks).toString('utf8');}
export async function jsonBody(req:Request){try{return JSON.parse(await readBody(req));}catch(e){if(e instanceof AppError)throw e;throw new AppError('Format data tidak sah.');}}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}});}
export async function notifyOperations(event:string,detail:Record<string,unknown>={}){const target=process.env.ALERT_WEBHOOK_URL;if(!target)return;try{const url=new URL(target);if(url.protocol!=='https:')throw new Error('Webhook must use HTTPS');await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:`RB Post alert: ${event}`,event,...detail}),signal:AbortSignal.timeout(5_000)});}catch(error){console.error(JSON.stringify({event:'alert_failed',source:event,type:error instanceof Error?error.name:'unknown'}));}}
export async function errorResponse(error:unknown){if(error instanceof z.ZodError)return json({error:error.issues[0]?.message||'Input tidak sah.'},400);if(error instanceof AppError)return json({error:error.message,code:error.code},error.status);const detail={type:error instanceof Error?error.name:'unknown',at:new Date().toISOString()};console.error(JSON.stringify({event:'request_failed',...detail}));await Promise.allSettled([logTechnical(null,null,'request_failed',detail),notifyOperations('request_failed',detail)]);return json({error:'Ada masalah memproses permintaan. Cuba lagi sebentar.'},500);}
export async function logTechnical(userId:string|null,postId:string|null,code:string,detail:Record<string,unknown>={}){try{await db().from('technical_errors').insert({user_id:userId,post_id:postId,code,detail});}catch{console.error('technical_log_unavailable',{code});}}
